### ISSUE TITLE
Tinyinfo Micro

### ISSUE THREAD

**Issue by Lion-Craft** [Lion-Craft/Tinyinfo#124]
# Tinyinfo Micro
## What is Tinyinfo Micro?
Tinyinfo Micro would be a version of Tinyinfo with less features and lower quality images.
## Why?
Currently (Between V3 Prerelease 1 and 2) Tinyinfo is about 9.1 MB in size. This is quite big compared to v1.x or even v2.0 SP x. With optimizations and extras removed the size can be decreased significantly.

**Comment by gemmebacon** [comment]
I think a smaller version of Tinyinfo is a great idea, but I think 9.1MB is still acceptable

**Comment by Lion-Craft** [comment]
> I think a smaller version of Tinyinfo is a great idea, but I think 9.1MB is still acceptable

Thanks, will start working on a v3µ release

**Comment by Lion-Craft** [comment]
Tinyinfo Micro has been added to the latest prerelease and SECURITY.md.
I was able to reduce the final size to about 850kb which is a significant difference.

Closing this issue.
