### ISSUE TITLE
Repoting wrong vram amount

### ISSUE THREAD

**Issue by gemmebacon** [Lion-Craft/Tinyinfo#133]
Tinyinfo V3 and micro is displaying wrong vram amount for my gpu

I have an Radeon RX6600XT 8GB gpu but Tinyinfo is reporting of it having 7GB of vram

![Screenshot 2023-11-20 013004](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/bf5db13e-f976-40c0-b6e3-333ce97d467e) 

![Screenshot 2023-11-20 012916](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/1aa62c66-abc4-4e52-8c02-dff8548827aa)

It's supposed to say "VRAM Amount: 8.00GB", but it says "VRAM Amount: 7.00GB"

![Screenshot 2023-11-20 013213](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/b7d394c3-76ed-41b4-964a-1d9f382720b1)

I honestly don't know why it does that

**Comment by Lion-Craft** [comment]
okay, finally came around to looking at this weird bug again. i cant get vram amount values to exactly match up with anything but theyre close enough to assume the difference comes from something like hardware reserved memory.
