### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by gemmebacon** [Lion-Craft/Tinyinfo#134]
When I open Tinyinfo on my laptop it displays an error

![Screenshot 2023-11-20 015828](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/672d0bcc-fbde-4926-8d68-7287ecf488b8)

[Error details](https://github.com/Lion-Craft/Tinyinfo/files/13405011/message.txt)

When I click Continue it starts, but the splash is still there

![Screenshot 2023-11-20 020133](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/1a53703e-b054-4830-ac44-a461f93e61b7)

If I click refresh it displays the same error

RAM, Motherboard, BIOS, Battery, Disk and Network pages are blank

![Screenshot 2023-11-20 020538](https://github.com/Lion-Craft/Tinyinfo/assets/85118845/c6bfb3a7-5af3-4d81-b781-e5a66903c4d1)

When I click on "Start" it just closes

**Comment by Lion-Craft** [comment]
Appears to be caused during the gpu info loading...

**Comment by Lion-Craft** [comment]
Huh my ThinkPad T60 does something similar only more catastrophically...

Mind posing your specs @gemmebacon?

**Comment by gemmebacon** [comment]
@Lion-Craft My specs are i9 9900k, 16GB of g.skill ram, AsRock z390 pro4 mb and a rtx 3060 ti 8GB

**Comment by Lion-Craft** [comment]
Bug appears to have been added in commit 2650107d5a051cf8e862e29cd64622e0cae5db35 when checking the GPU manufacturers. Seems to be a rather easy fix.

**Comment by gemmebacon** [comment]
I forgot to mention, I wrote this bug report about my laptop which has an i5 7200u and 8GB of ram, but I provided specs for my main pc because it has the same problem

**Comment by Lion-Craft** [comment]
@gemmebacon How many Graphics devices do both computers have? (ie. only igpu, igpu + dedicated, dedicated only, dual dedicated, etc.)

**Comment by gemmebacon** [comment]
Both have an igpu and a dedicated gpu

**Comment by Lion-Craft** [comment]
Alright thanks, gonna have to do some debugging...

**Comment by Lion-Craft** [comment]
Figured out the issue, the "manufacturer" array's length (which is used to check if nvidia graphics are present or not) was set to 2 which is obviously problematic with more than 2 video controllers. 

Gonna work on a fix now.

**Comment by Lion-Craft** [comment]
Opening this issue again due to the fix being applied only to the full version. Micro still needs to be updated.

**Comment by Lion-Craft** [comment]
Fixed for Micro in #136
