### ISSUE TITLE
Bug "Managed Debugging Assistant 'RaceOnRCWCleanup'"

### ISSUE THREAD

**Issue by HoudaifaBouamine** [Lion-Craft/Tinyinfo#25]
![image](https://github.com/Lion-Craft/Tinyinfo/assets/119418687/44da0a47-3e22-491b-b8c9-72721732667a)

This bug appear when closing the program while refreshing the hardware info

**Comment by Lion-Craft** [comment]
This exception appears to be thrown when the refresh thread is running. Possible fix would be to stop the thread before allowing the program to close.
