### ISSUE TITLE
XML and JSON export

### ISSUE THREAD

**Issue by Lion-Craft** [Lion-Craft/Tinyinfo#60]
Recently data export as Text was implemented thus it would also be useful to add XML and JSON exports which could also be created via a cmd argument if other applicatios want to use the data.

**Comment by magicalunicor** [comment]
Hi! I'm on it :)

**Comment by Lion-Craft** [comment]
Redoing the JSON export the ape way now due to the new nvapi data

**Comment by Lion-Craft** [comment]
JSON export is fully working now
