### ISSUE TITLE
Partially wrong output formatting

### ISSUE THREAD

**Issue by Lion-Craft** [Lion-Craft/Tinyinfo#71]
Most likely introduced with Pull Request #70 some info items' formatting is incorrect like missing line breaks.

**Comment by magicalunicor** [comment]
Would you mind showing how the output should be vs how the output is? Thanks!

**Comment by Lion-Craft** [comment]
> Would you mind showing how the output should be vs how the output is? Thanks!

Sorry that im seeing your comment so late, ive already fixed the issue but here is the ideal formatting anyway:
_**normal:**_
[component name]:
[tab][info item name]: [info item]
_**for "subtitles" (ie ram banks or nics or drives):**_
[component name]:
[tab][subtitle]:
[tab][tab][info item name]: [info item]
